server:
  port: 9788

#  ssl:
#    key-store: classpath:keystore/soa.p12
#    key-store-type: PKCS12
#    key-store-password: 123123
#    key-alias: soa
#    enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://pg:5432/studs"
    username: "s311690"
    password: "frxR7QvRq6rTzu0A"
#    url: "jdbc:postgresql://localhost:5432/postgres"
#    username: "postgres"
#    password: "postgres"

  jpa:
    hibernate:
      ddl-auto: "create"
